# Generated by Django 5.0.7 on 2024-09-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RemovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passphoto', models.ImageField(blank=True, null=True, upload_to='passphotos/')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('Date_of_birth', models.DateField(default='1947-01-01')),
                ('Address', models.TextField()),
                ('Course', models.CharField(max_length=255)),
                ('Year_of_passing', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passphoto', models.ImageField(blank=True, null=True, upload_to='passphotos/')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('Date_of_birth', models.DateField(null=True)),
                ('Address', models.TextField()),
                ('Course', models.CharField(max_length=100)),
                ('Year_of_passing', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('gender', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
